### ISSUE TITLE
Decoding Apple Color Emoji font

### ISSUE THREAD

**Issue by klaas** [cc4966/emjc-decoder#4]
I'm trying to decode an emjc asset that I got from the Apple Color Emoji font from iOS 13.2.

I was able to extract the width, height and size using your functions. But the decoding itself fails, because `lzfse_decode_buffer` returns 0.

Do you have any ideas regarding this? Maybe Apple uses yet another compression?

**Comment by cc4966** [comment]
This was probably due to interface bug fixed by https://github.com/cc4966/emjc-decoder/pull/5.
